### ISSUE TITLE
where do the other operations in the Math module go?

### ISSUE THREAD

**Issue by kjx** [gracelang/language#69] opened 2016-02-23 23:40 UTC

**Comment by apblack** [comment] 2016-02-25 23:39
I'm sympathetic to leaving the trig and the log functions into a module.  At some point we will need to address extending number with operations like radians and degrees, to create angle objects, that understand trig functions, but this does not seem like a high priority.  

It also seems clear to me that random ought to be a module, with methods like
```grace
    random.fractionLessThanOne
        // a pseudo-random number x such that 0 ≤ x < 1 using a shared module-local generator
    random.between (lwb) and (upb)
        // a pseudo-random integer x such that lwb ≤ x ≤ upb using a shared module-local generator
    random.iteratorFractionLessThanOne
        // an iterator over an infinite stream of pseudo-random numbers x such that 0 ≤ x < 1.  Request next
        // on this generator to get a new pseudo-random number.  The yielded numbers are independent
        // of any other random numbers.
    random.iteratorBetween (lwb) and (upb)
        // an iterator over an infinite stream of pseudo-random integers x such that lwb ≤ x ≤ upb.  
        // Request next on this generator to get a new pseudo-random number.  The yielded 
        // numbers are independent of any other random numbers,
```
and maybe others.

**Comment by KimBruce** [comment] 2016-02-26 05:08
I’m not sure that having separate radian and degree numbers is necessary, and might create a lot more complexity (after all we would need to do operations on them with both similar objects and numbers and banning overloading might complicate that).  I’d want to at least look at what others have done before introducing them.

I don’t have strong feelings on keeping trig and log in a separate module as it seems easier not to do that, but I can understand if you want to leave open the option of dimensional numbers.

I’m a bit worried about having so many options for randoms, though I suspect I would only teach students the non-iterator version.

Kim

**Comment by kjx** [comment] 2016-02-26 10:00
What's the principle? How do we decide? 

If we supported (1 .. 6) chooseAtRandom  then I guess we could also support [ "north", "south", "east", "west" ] chooseAtRandom for any (fixed-size) collection?

**Comment by apblack** [comment] 2016-02-26 19:47
Kim, it was you that introduced the integer version of random.  I agree that it's convenient.  The problem, though, is that with a songle global RNG, uses of random in different modules are not independent.  This is certainly something that I can see _some_ instructors wishing to talk about.

An example of this is @kjx's suggestion of `chooseAtRandom`, which Smalltalk calls `atRandom` (a better name, in my opinion, by analogy with `at 6`).  They are methods on the collection objects.  They are not truly pseudo-random, though, because all collections share the same RNG.

There are alternative ways of getting multiple independent RNGs, other than iterators. But the iterator approach seems clean, and having created, say

    def randoms = random.iteratorBetween 0 and 9

a programmmer would then write

    randoms.next

to get the next pseudo-random number, which seems elegant.

> What's the principle? How do we decide?

Principles?

1. Grace is object-oriented.  So we prefer to say things like `n.log10` rather than `log10 n`, even though it looks weird at first.

2. Whenever possible, stuff should be moved out of the core language and into modules — as discussed in #53.

**Comment by KimBruce** [comment] 2016-02-26 20:01
I do think we need all four in order to get correct uses of random.  I just wish they didn’t look so similar, or that we could stash them in different places so students wouldn’t get confused.

No real suggestions however.

**Comment by kjx** [comment] 2016-02-27 00:28
> uses of random in different modules are not independent

this is important from a security point of view - and probably gives rise to another principle: minimise dependencies between modules!  That says that choose shouldn't be in collections, because it adds a dependency between collection and random, and collections is already bad enough .

> students wouldn’t get confused

I fear we'll have many more sources of confusion that just this, I'm afraid.

**Comment by apblack** [comment] 2016-04-06 00:10
There is now a random module in _minigrace_, and it is described in the _BasicObjects_ document.  It doesn't have the iterator forms, just the ones with the global RNG.  Consider this a work in progress.

**Comment by apblack** [comment] 2016-04-16 01:36
As for the trig methods in math, log, ln, etc: it seems clear that in an OO language they should be operations on Number objects. Accordingly, they now are.

There might be a case for retaining `math` as a module, though.  We made a weak commitment to the "functional first" style, in which it's much more reasonable to write `sin(π/4)` than `(π/4).sin`.   Is this commitment sufficient to retain `math` as a module, and thus violate our other principle, which was to have only one way of saying stuff?

Of course, a "functional first" dialect could itself declare the trig functions as top-level methods.  Maybe we should start sketching out dialects?

**Comment by apblack** [comment] 2017-02-10 23:33
I'm closing this because it's done.  There is useful discussion here about the `iterator` forms of the PRNGs, but we can still read that once the issue is closed.

For the record, I'll state that I agree that we _need_ the iterator forms.  Why don't we have them? 
The short answer is that they are not built into JavaScript, so I would have to either
 * find a package that implements them, and interface to that, or 
 * implement them myself.

Neither has been a high priority.  If someone else wants to do this, please go ahead!

**Closed by apblack** 2017-02-10 23:33 UTC
Labels: 3:later, libraries
